config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  get "mis_publicaciones", to: "posts#mis_publicaciones"

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :posts do
    resources :reviews, only: [:create, :update]
  end
  resources :reviews, only: [:edit, :destroy]
end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id         :bigint           not null, primary key
#  specie     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Animal < ApplicationRecord
  has_many :posts
  # enum specie: {
  #   'perro' => 1, 'gato' => 0
  #  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  address     :string
#  description :text
#  latitude    :float
#  longitude   :float
#  post_type   :boolean
#  status      :string
#  reward      :boolean
#  user_id     :bigint           not null
#  animal_id   :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  title       :text
#
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  has_many :reviews, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model

  pg_search_scope :search_by_description_and_address_and_title,
  against: [ :description, :address, :title],
  using: {
  tsearch: { prefix: true }
  }

  validates :address, :description, :title, :photos, presence: true
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :bigint           not null, primary key
#  content    :text
#  post_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_one_attached :photo
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @posts = Post.search_by_description_and_address_and_title(params[:query])
    else
      @posts = Post.all
    end
  end

  def new
    @post = Post.new
    @animal = Animal.all
  end

  def show
    @animal = Animal.all
    @review = Review.new
    @markers = {
      lat: @post.latitude,
      lng: @post.longitude,
      info_window: render_to_string(partial: "info_window", locals: { post: @post }),
      image_url: helpers.asset_url("Simbolo-patitas.png")
    }

    # @post_id = @post.id
    # @posts = Post.geocoded
    # @markers = @posts.map do |post|
    #   if post.id == @post_id
    #     photo = "logo.png"
    #   else
    #     photo = "Simbolo-patitas.png"
    #   end
    #   {
    #     lat: post.latitude,
    #     lng: post.longitude,
    #   }
    # end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def mis_publicaciones
    @posts = Post.where(user_id: current_user.id)
    @review = Review.new
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :address, :description, :reward, :animal_id, :post_type, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_post, only: :update
  before_action :set_review, only: [:update, :destroy]

  def create
    @review = Review.new(review_params)
    @post = Post.find(params[:post_id])
    @review.post = @post
    @review.user = current_user
    if @review.save
      redirect_to post_path(@post)
    else
      render "posts/show", status: :unprocessable_entity
    end
  end

  def update
    if @review.update(review_params)
      redirect_to post_path(@review.post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @review.destroy
    redirect_to post_path(@review.post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="container chatroom mt-5"
  data-controller="chatroom-subscription "
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">
  <h1 id="titulo" class="rojo">Chat</h1>
  <div class="messages background-chat" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
        <div class="message-row d-flex  <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
          <div class="d-flex <%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
          </div>
        </div>
      <% end %>
  </div>

  <%= simple_form_for [@chatroom, @message],
    remote: true,
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|%>

    <%= f.input :content,
      label: false,
      placeholder: "Escribe tu mensaje",
      wrapper_html: {class: "flex-grow-1"} %>
    <%= f.submit "Enviar", class: "ml-1 btn btn-danger mb-3" %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patitas a Casa - Encuentra y reporta peluditos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <script src="https://kit.fontawesome.com/44d4a8fc4e.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.js" integrity="sha512-CX7sDOp7UTAq+i1FYIlf9Uo27x4os+kGeoT7rgwvY+4dmjqV0IuE/Bl5hVsjnQPQiTOhAX1O2r2j5bjsFBvv/A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.js" integrity="sha512-CX7sDOp7UTAq+i1FYIlf9Uo27x4os+kGeoT7rgwvY+4dmjqV0IuE/Bl5hVsjnQPQiTOhAX1O2r2j5bjsFBvv/A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <% if message.user.photo.key %>
      <%= cl_image_tag(message.user.photo.key, class: "avatar-chat") %>
    <% else %>
      <%= image_tag("http://www.medqualityassurance.org/views/images/default_user.png", class: "avatar-chat") %>
    <% end %>
    <strong><%= message.user.email %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% @posts.each do |post| %>
  <h2><%= post.description %></h2>

<% end %>

app/views/posts/_info_window.html.erb
<h2><%= post.title %></h2>
<p><%= post.address %></p>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="background-form rounded p-3 shadow mt-5">
        <h2  class=" text-center" id="titulo">Edita tu post </h2>

        <%= simple_form_for @post do |f| %>
          <%= f.input :title, label: "Título" %>
          <%= f.input :status, label: "Estado" %>
          <%= f.input :address, label: "Dirección donde se vió el peludo:",
          input_html: {data: {address_autocomplete_target: "address"}},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
          %>
          <%= f.input :latitude, label: "Latitud" %>
          <%= f.input :longitude, label: "Longitud" %>
          <%= f.input :description, label: "Descripción física" %>
          <%= f.input :reward, label: "Recompensa",
            required: true,
            autofocus: true,
            input_html: { autocomplete: "Recompensa?" }%>
          <div class="text-center m-3"><%= f.button :submit, "Actualizar", class: 'btn btn-red' %> </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class=" banner-image mb-1"></div>

<div class="container d-flex justify-content-center">
  <div>


    <div class="container shadow p-3 mb-5 bg-white rounded " style="height: 220px; background-color: #d1fffd">
      <h3 class="text-center mt-5 azul " id="titulo"> Para todos los peludos que necesiten volver a casa, perdidos o encontrados </h3>
      <div class= "row d-flex ">
        <div class="col text-center m-3  d-flex justify-content-center">
            <%= link_to "Busco a mi peludo", new_post_path(:option => "perdido"), class: "btn btn-red" %>
        </div>
        <div class="col text-center m-3 d-flex justify-content-center">
            <%= link_to "Encontré un peludo", new_post_path(:option => "encontrado"), class: "btn btn-red" %>
        </div>
    </div>

  </div>

    <br>
    <h1 class="text-center rojo mb-5" id="titulo"> Estos peludos buscan su casa </h1>
    <div class="row ">
        <% @posts.each do |post| %>
        <div class="col-sm-4  d-flex justify-content-around ">
          <div class="card shadow mb-5 bg-white rounded text-center d-flex rounded-5 pb-5 cards" style="width: 300px" >
            <% if post.photos.attached?%>
                <%= link_to post_path(post) do %>
                  <%= cl_image_tag post.photos.first.key, height: 225, width: 300, crop: :fill, class: "card-img-top rounded" %>
                <% end %>
              <% end %>
              <center>
              <span class="align-items-center position-absolute top-95 start-50 translate-middle ">
              <% if post.post_type == true %>
              <p class="tag tag-red">  <%= 'Perdido' %> </p>
              <%else %>
              <p class="tag tag-blue"> <%= 'Encontrado' %> </p>
              <% end %>
              </span>
              </center>
              <span class="undecorated-link mt-3">
                <%= link_to post_path(post) do %>
                <h5 class="card-title text-dark mt-2" id="titulo-card" > <%= post.title %> </h5>
              <% end %>
              <p> <%= post.address %> </p>
              </span>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/mis_publicaciones.html.erb
  <div class="container mb-3 mt-5">
  <div class="mt-5"></div>
    <h2 class="text-center  mt-5 pt-3 rojo" id="titulo" > Mis publicaciones </h2>
      <div class="row justify-content-around mt-5">
        <% @posts.each do |post| %>
        <div class="col-sm-4 d-flex justify-content-around">
            <div class="card  d-flex justify-content-between shadow mb-5 bg-white rounded cards-publicaciones" style="width: 333px ">
              <% if post.photos.attached?%>
                  <%= link_to post_path(post) do %>
                    <%= cl_image_tag post.photos.first.key, height: 250, width: 333, crop: :fill, class: "card-img-top rounded card-image" %>
                  <% end %>
              <% end %>

              <div class="card-text mt-3">
                <span class="undecorated-link pt-3 ">
                  <%= link_to post_path(post) do %>
                  <h5 class="card-title text-dark  " id="titulo-card" > <%= post.title %> </h5>
                  <% end %>
                </span>
                <div class="card-body ">
                  <p><%= post.address %></p>
                  <p><%= post.description %></p>
                </div>
              <% if post.post_type == true %>
                <div class="card-stats tag-red">
                  <span class="stat text-center ">
                  <% if post.post_type == true %>
                  <p class="stat ">  <%= 'Perdido' %> </p>
                  <%else %>
                  <p class="stat "> <%= 'Encontrado' %> </p>
                  <% end %>
              <%else %>

                <div class="card-stats tag-blue">
                  <span class="stat text-center ">
                  <% if post.post_type == true %>
                  <p class="stat ">  <%= 'Perdido' %> </p>
                  <%else %>
                  <p class="stat "> <%= 'Encontrado' %> </p>
                  <% end %>
              <%end%>

                  </span>
                  <div class="stat m-3 text-center">
                    <%= post.created_at.strftime("Creado el  %d/%m/%Y") %>
                  </div>
                </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class = "publicaciones">
  </div>

app/views/posts/show.html.erb
  <div class=" d-block justify-content-center mt-5 mb-5">
    <div class="card mb-3 bg-white rounded border-0" style="width: 100%; ">
      <div class="card-body d-flex">
        <div class="imagen shadow  col-md-4 offset-md-1  bg-white rounded-4 p-3 ">

          <div>

            <div id= "carouselExampleIndicators" class="carousel slide pt-4" data-ride="carousel">
              <div class="carousel-inner ">
                <% @post.photos.each_with_index do |photo, index| %>
                <div class="carousel-item <%= "active" if  index == 0 %> ">
                    <%#= cl_image_tag photo.key, height: 400, width: 500, class:"card-img-top mb-3" , crop: :fill %>
                    <img id="img-car" class=" w-100 card-img-top " src="<%=photo.url %>" alt="slide" style='  width: 400px'>
                </div>
                <% end %>
              </div>
              <a class="carousel-control-prev " href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-dark rounded-circle" aria-hidden="true" ></span>
                <span class="sr-only">Anterior</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-dark rounded-circle" aria-hidden="true"></span>
                <span class="sr-only">Siguiente</span>
              </a>
            </div>

            <div>
              <div id='map' style='w-100; height: 300px;' class="mt-2"
              data-controller="map" data-map-marker-value="<%=@markers.to_json%>">
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center ">
            <% if current_user.present? %>
              <% if current_user.id == @post.user_id %>
                <%= link_to "", edit_post_path(@post), class: "fa-solid fa-pen-to-square mt-3", id: "edit-buttom" %>
                <%= button_to "", post_path(@post), data: { confirm: "Are you sure?" }, method: :delete, class: "fa-regular fa-trash-can m-3", id: "delete-buttom" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div  class="card-info shadow border-0 rounded-4 p-4 col-md-5 offset-md-1 ">
          <div class="d-block fs-3">
            <h4 class="card-title text-center pb-2" id="titulo"> <%= @post.title %> </h4>
          </div>
          <span class=" text-center position-absolute top-95 start-50 translate-middle  mt-3 mb-5 ">
          <% if @post.post_type == true %>
            <p class="tag-show tag-red">  <%= 'Perdido' %> </p>
          <%else %>
           <p class="tag-show tag-blue"> <%= 'Encontrado' %> </p>
          <% end %>
          </span>

          <br>
          <div class="d-block fs-5 pt-5 pb-3">
            <i class="fa-solid fa-paw"></i>
            <strong> <%= "Peludo :" %> </strong> <%= @post.animal.specie %>
          </div>
          <div class="d-block fs-5 pb-3 ">
            <i class="fa-solid fa-magnifying-glass-location"></i>
            <strong> <%= "Dirección :" %> </strong> <%= @post.address %>
          </div>
          <div class="d-block fs-5 pb-3">
            <i class="fa-solid fa-file-lines"></i>
            <strong> <%= "Descripción :" %> </strong> <%= @post.description %>
          </div>
          <div class="d-block fs-5 pb-3">
            <i class="fa-solid fa-coins"></i>
            <% if @post.post_type == true %>
              <strong> <%= "Recompensa :" %> </strong> <%= @post.reward ? 'Si' : 'No' %>
            <% end %>
          </div>
          <div class="d-block fs-5 pb-3">
            <i class="fa-regular fa-paper-plane"></i>
            <strong> <%= "Estado :" %> </strong> <%= @post.status %>
          </div>
          <div class="d-block fs-5 pb-3">
            <i class="fa-regular fa-calendar"></i>
            <strong> <%= "Fecha de creación :" %> </strong> <%= @post.created_at.strftime("  %d/%m/%Y") %>
          </div>
          <div class="d-flex justify-content-center">
            <div class="d-block mb-5 blue-background rounded-4 col-4 mt-3  text-center">
            <% if current_user.present? %>
              <%= link_to "", chatroom_path(Chatroom.first), class: "fa-regular fa-comments m-3 justify-content-center", id: "chat-buttom" %>
              <h5>Iniciar chat</h5>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class=" container d-flex justify-content-around row  text-center col-12 ml-0 mr-0 border-0">
      <div class="col-md-4  mx-auto  bg-white rounded-4 pl-5">
        <h3 class= "text-center pt-5">Comentarios</h3>
        <% if @post.reviews.empty? %>
          <small><em class="text-muted ml-5">Sé el primero en dejar un comentario</em></small>
        <% end %>
        <% @post.reviews.each do |review| %>
          <div>
            <div class= "background-comments rounded p-3">
              <p class="mb-0"><%= review.content %></p>
              <small><%= distance_of_time_in_words_to_now(review.created_at) %> ago</small>
            </div>
            <div class="d-flex justify-content-center mt-2">
              <% if current_user.present? %>
                <% if current_user == review.user %>
                  <span id= "btn-<%= review.id %>">  <%= link_to "", post_review_path(review), class: 'fa-solid fa-pen-to-square m-1 ', id: "edit-buttom-comments", onclick: "showContent()" %> </span>
                  <%= button_to "", review_path(review), data: { confirm: "Are you sure?" }, method: :delete, class: "fa-regular fa-trash-can m-1", id: "delete-buttom-comments" %>
                <% end %>
              <% end %>
            </div>
            <div id= "content-<%= review.id %>" style= "display: none">
              <%= simple_form_for [@post, review], method: :put, url: post_review_path(@post, review) do |f| %>
                <%= f.input :content%>
                <%= f.submit class:"btn btn-danger" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class=" col-md-5 offset-md-1  mx-auto pr-5">
        <div class="bg-white rounded py-5 pr-5">
          <h4>Agrega tu comentario</h4>
          <%= simple_form_for [@post, @review] do |f| %>
            <%= f.input :content,placeholder: "Agrega tu comentario aquí...", label: "Comentario", class:"col-4" %>
            <%= f.submit "Comentar", class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<script>
  function showContent() {
    const id = event.currentTarget.href.split("/")[4]
    event.preventDefault()
    $(`#content-${id}`).show()
  }
</script>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom fixed-top me-auto ">
  <div class="container-fluid justify-content-between d-flex">
   <!--<div class="grad-bar"></div>-->
      <%= link_to "/", class: "brand" do %>
        <%= image_tag "Logotipo-patitas.png", class: "logo-img" %>
      <% end %>

      <div class=" container col-4 text-center ">
        <%= form_with url: posts_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Busca a tu peludito"%>
          <%= submit_tag "Buscar", class: "btn btn-flat ml-1" %>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Publicar", new_post_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Mis publicaciones", mis_publicaciones_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, class: "avatar-img dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "http://www.medqualityassurance.org/views/images/default_user.png", class: "avatar-img dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Editar mi contraseña", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Salir", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Inicia Sesión", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
  </div>
</div>









<!-- https://i.gyazo.com/16694022146c01109d007d57d640b96e.jpg  lupa sola -->
<!-- -->
<!-- color rojo: #e02d47-->
<!-- color azul: #02bbb5 -->